version: '2'

services:
  caliper_1.4:
      container_name: caliper_1.4
      image: hyperledger/caliper:0.3.0
      command: launch master
      environment: 
        - CALIPER_BIND_SUT=fabric:1.4.1
        - CALIPER_BENCHCONFIG=benchmarks/scenario/simple/config.yaml
        - CALIPER_NETWORKCONFIG=networks/Ureca/network-config.yaml
      volumes:
        - ./caliper-benchmarks-local:/hyperledger/caliper/workspace
      network_mode: host
