version: '2'

networks:
  basic:

services:
  orderer1.ordererorg1:
    container_name: orderer1.ordererorg1
    image: ${FABRIC_ORDERER_FIXTURE_IMAGE}:${ARCH}-${FABRIC_VERSION}
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=ordererorg1msp
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
      - ./channel-artifacts:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/ordererorg1/orderers/orderer1.ordererorg1:/etc/hyperledger/msp/orderer
    networks:
      - basic

  peer1.peerorg1:
    container_name: peer1.peerorg1
    image: ${FABRIC_PEER_FIXTURE_IMAGE}:${ARCH}-${FABRIC_VERSION}
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.peerorg1
      - CORE_CHAINCODE_LOGGING_LEVEL=warning
      - CORE_PEER_LOCALMSPID=peerorg1msp
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer1.peerorg1:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.peerorg1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=grpc://localhost:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_CHAINCODE_GOLANG_RUNTIME=${FABRIC_BASEOS_FIXTURE_IMAGE}:${ARCH}-${FABRIC_BASE_VERSION}
      - CORE_CHAINCODE_BUILDER=${FABRIC_BUILDER_FIXTURE_IMAGE}:${ARCH}-${FABRIC_VERSION}
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/peerorg1/peers/peer1.peerorg1/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/peerorg1/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer1.ordererorg1
    networks:
      - basic

  peer2.peerorg1:
    container_name: peer2.peerorg1
    image: ${FABRIC_PEER_FIXTURE_IMAGE}:${ARCH}-${FABRIC_VERSION}
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer2.peerorg1
      - CORE_CHAINCODE_LOGGING_LEVEL=warning
      - CORE_PEER_LOCALMSPID=peerorg1msp
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer2.peerorg1:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.peerorg1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=grpc://localhost:7151
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_CHAINCODE_GOLANG_RUNTIME=${FABRIC_BASEOS_FIXTURE_IMAGE}:${ARCH}-${FABRIC_BASE_VERSION}
      - CORE_CHAINCODE_BUILDER=${FABRIC_BUILDER_FIXTURE_IMAGE}:${ARCH}-${FABRIC_VERSION}
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_basic
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7151:7051
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/peerorg1/peers/peer2.peerorg1/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/peerorg1/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer1.ordererorg1
    networks:
      - basic

  cli:
    container_name: cli
    image: ${FABRIC_TOOLS_FIXTURE_IMAGE}:${ARCH}-${FABRIC_VERSION}
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer1.peerorg1:7051
      - CORE_PEER_LOCALMSPID=peerorg1msp
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/crypto/peerOrganizations/peerorg1/users/Admin@peerorg1/msp
    working_dir: /opt/gopath/src
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config:/etc/hyperledger/crypto/
      - ./channel-artifacts:/etc/hyperledger/channel-artifacts
      - ../chaincode:/opt/gopath/src
    depends_on:
      - orderer1.ordererorg1
      - peer1.peerorg1
      - peer2.peerorg1
    networks:
      - basic
